name: Makefile CI

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

#    - name: configure
#      run: ./configure

#    - name: Install dependencies
#      run: make

  - name: One Semester
    run: make one-semester-html-all


